// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

package go_micro_srv_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

//单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e5e5ab05dfa973d5, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
}

func init() {
	proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor_e5e5ab05dfa973d5)
}

var fileDescriptor_e5e5ab05dfa973d5 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x14, 0xc4, 0xbf, 0xf4, 0x7f, 0x5e, 0xaa, 0x7e, 0xc2, 0x0b, 0xb0, 0x60, 0x41, 0x94, 0x82, 0xd4,
	0x55, 0x90, 0xca, 0x11, 0xb2, 0xa8, 0xb2, 0x75, 0xd7, 0x08, 0x4a, 0xfc, 0x94, 0x5a, 0x22, 0x76,
	0xb0, 0xdd, 0x72, 0x35, 0x38, 0x06, 0x37, 0x42, 0x75, 0x1a, 0x6a, 0x84, 0x8a, 0xba, 0xf3, 0xbc,
	0xf1, 0xcf, 0x33, 0xb6, 0x0c, 0xd3, 0x5a, 0x2b, 0xab, 0xee, 0x0a, 0x25, 0x8d, 0x28, 0x65, 0x85,
	0xd2, 0xfa, 0xeb, 0xd4, 0xb9, 0x84, 0x96, 0x2a, 0xad, 0x44, 0xa1, 0x55, 0x6a, 0xf4, 0x36, 0xf5,
	0xfc, 0xe4, 0x23, 0x80, 0x28, 0x3b, 0x68, 0x32, 0x81, 0x8e, 0xe0, 0x34, 0x88, 0x83, 0x59, 0xc8,
	0x3a, 0x82, 0x93, 0x18, 0x22, 0x8e, 0xa6, 0xd0, 0xa2, 0xb6, 0x42, 0x49, 0xda, 0x71, 0x86, 0x3f,
	0x22, 0xe7, 0x30, 0x78, 0x43, 0x51, 0xae, 0x2d, 0xed, 0xc6, 0xc1, 0xac, 0xcf, 0xf6, 0x8a, 0x64,
	0x00, 0x85, 0x92, 0x76, 0x25, 0x24, 0x6a, 0x43, 0x7b, 0x71, 0x77, 0x16, 0xcd, 0xa7, 0xe9, 0xb1,
	0x22, 0x69, 0xd6, 0xee, 0x65, 0x1e, 0x46, 0xae, 0x20, 0xdc, 0xa2, 0x31, 0xf8, 0xf2, 0x28, 0x38,
	0xed, 0xbb, 0xf0, 0x51, 0x33, 0xc8, 0x79, 0x52, 0x41, 0xf8, 0x4d, 0xfd, 0x2a, 0x7e, 0x0d, 0x51,
	0xb1, 0x31, 0x56, 0x55, 0xa8, 0x77, 0x6c, 0x53, 0x1c, 0xda, 0x51, 0xce, 0x77, 0xbd, 0x95, 0x16,
	0xa5, 0x90, 0xae, 0x77, 0xc8, 0xf6, 0x8a, 0x5c, 0xc0, 0x70, 0x63, 0x1a, 0xa8, 0xd7, 0x18, 0x3b,
	0x99, 0xf3, 0xe4, 0x3d, 0x80, 0x91, 0x46, 0x53, 0x2b, 0x69, 0x90, 0x50, 0x18, 0x16, 0x1a, 0x57,
	0x16, 0x9b, 0xcc, 0x11, 0x6b, 0x25, 0x59, 0x40, 0xe4, 0xdd, 0xcb, 0x05, 0x47, 0xf3, 0xdb, 0x3f,
	0x2f, 0xde, 0xae, 0x99, 0x4f, 0x92, 0x1c, 0xc6, 0x9e, 0x34, 0xb4, 0xeb, 0x9e, 0xf0, 0xc4, 0x93,
	0x7e, 0xa0, 0xc9, 0x18, 0x60, 0x81, 0x96, 0xe1, 0xeb, 0x06, 0x8d, 0x9d, 0x7f, 0x06, 0x30, 0x59,
	0xae, 0x45, 0x5d, 0x0b, 0x59, 0x2e, 0x51, 0x6f, 0x51, 0x93, 0x27, 0x38, 0xcb, 0x5c, 0x7f, 0xff,
	0x2f, 0x9c, 0x16, 0x75, 0x99, 0x1c, 0xdf, 0xd6, 0x3e, 0x57, 0xf2, 0x8f, 0x3c, 0xc0, 0xff, 0x05,
	0x5a, 0x8f, 0x33, 0xe4, 0xe6, 0x38, 0x78, 0x68, 0x7b, 0xda, 0xf1, 0xcf, 0x03, 0xf7, 0xd1, 0xef,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x11, 0xa6, 0xfe, 0x0f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShippingServer service

type ShippingServerClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type shippingServerClient struct {
	c           client.Client
	serviceName string
}

func NewShippingServerClient(serviceName string, c client.Client) ShippingServerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.consignment"
	}
	return &shippingServerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shippingServerClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingServer.CreateConsignment", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServerClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingServer.GetConsignments", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingServer service

type ShippingServerHandler interface {
	CreateConsignment(context.Context, *Consignment, *Response) error
	GetConsignments(context.Context, *GetRequest, *Response) error
}

func RegisterShippingServerHandler(s server.Server, hdlr ShippingServerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ShippingServer{hdlr}, opts...))
}

type ShippingServer struct {
	ShippingServerHandler
}

func (h *ShippingServer) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
	return h.ShippingServerHandler.CreateConsignment(ctx, in, out)
}

func (h *ShippingServer) GetConsignments(ctx context.Context, in *GetRequest, out *Response) error {
	return h.ShippingServerHandler.GetConsignments(ctx, in, out)
}
