// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consignment/consignment.proto

/*
Package go_micro_src_consignment is a generated protocol buffer package.

It is generated from these files:
	proto/consignment/consignment.proto

It has these top-level messages:
	Consignment
	Container
	Response
	Request
*/
package go_micro_src_consignment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 托运一批货物
type Consignment struct {
	Id         string       `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Descrition string       `protobuf:"bytes,2,opt,name=descrition" json:"descrition,omitempty"`
	Weight     int32        `protobuf:"varint,3,opt,name=weight" json:"weight,omitempty"`
	Containers []*Container `protobuf:"bytes,4,rep,name=containers" json:"containers,omitempty"`
	VesselId   string       `protobuf:"bytes,6,opt,name=vessel_id,json=vesselId" json:"vessel_id,omitempty"`
}

func (m *Consignment) Reset()                    { *m = Consignment{} }
func (m *Consignment) String() string            { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()               {}
func (*Consignment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescrition() string {
	if m != nil {
		return m.Descrition
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 集装箱
type Container struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId     string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CustomerId string `protobuf:"bytes,3,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	Origin     string `protobuf:"bytes,4,opt,name=origin" json:"origin,omitempty"`
}

func (m *Container) Reset()                    { *m = Container{} }
func (m *Container) String() string            { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()               {}
func (*Container) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

type Response struct {
	Created      bool           `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
	Consignments []*Consignment `protobuf:"bytes,2,rep,name=consignments" json:"consignments,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

type Request struct {
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.src.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.src.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.src.consignment.Response")
	proto.RegisterType((*Request)(nil), "go.micro.src.consignment.Request")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error)
	GetConsignments(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type shippingServiceClient struct {
	cc *grpc.ClientConn
}

func NewShippingServiceClient(cc *grpc.ClientConn) ShippingServiceClient {
	return &shippingServiceClient{cc}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.src.consignment.shippingService/CreateConsignment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/go.micro.src.consignment.shippingService/GetConsignments", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceServer interface {
	CreateConsignment(context.Context, *Consignment) (*Response, error)
	GetConsignments(context.Context, *Request) (*Response, error)
}

func RegisterShippingServiceServer(s *grpc.Server, srv ShippingServiceServer) {
	s.RegisterService(&_ShippingService_serviceDesc, srv)
}

func _ShippingService_CreateConsignment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Consignment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.src.consignment.shippingService/CreateConsignment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).CreateConsignment(ctx, req.(*Consignment))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShippingService_GetConsignments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShippingServiceServer).GetConsignments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.micro.src.consignment.shippingService/GetConsignments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShippingServiceServer).GetConsignments(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _ShippingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.micro.src.consignment.shippingService",
	HandlerType: (*ShippingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateConsignment",
			Handler:    _ShippingService_CreateConsignment_Handler,
		},
		{
			MethodName: "GetConsignments",
			Handler:    _ShippingService_GetConsignments_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/consignment/consignment.proto",
}

func init() { proto.RegisterFile("proto/consignment/consignment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 333 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x15, 0x5a, 0x69, 0x99, 0x1a, 0x1b, 0xf7, 0xa0, 0x1b, 0x4d, 0xb4, 0xd2, 0x98, 0xf4, 0x84,
	0x49, 0xfd, 0x04, 0x0e, 0x86, 0x2b, 0xde, 0xbc, 0x68, 0x5d, 0x26, 0x74, 0x12, 0xd9, 0xc5, 0x9d,
	0x6d, 0xfd, 0x34, 0x3f, 0xc3, 0x5f, 0x32, 0x05, 0x51, 0x8c, 0x69, 0xd3, 0xdb, 0xbc, 0x37, 0xf3,
	0x78, 0xef, 0x85, 0x85, 0x69, 0x65, 0x8d, 0x33, 0xb7, 0xca, 0x68, 0xa6, 0x42, 0x97, 0xa8, 0x5d,
	0x77, 0x8e, 0xeb, 0xad, 0x90, 0x85, 0x89, 0x4b, 0x52, 0xd6, 0xc4, 0x6c, 0x55, 0xdc, 0xd9, 0x47,
	0x1f, 0x1e, 0x8c, 0x92, 0x5f, 0x2c, 0x8e, 0xc1, 0xa7, 0x5c, 0x7a, 0x13, 0x6f, 0x16, 0x66, 0x3e,
	0xe5, 0xe2, 0x12, 0x20, 0x47, 0x56, 0x96, 0x1c, 0x19, 0x2d, 0xfd, 0x9a, 0xef, 0x30, 0xe2, 0x14,
	0x82, 0x77, 0xa4, 0x62, 0xe9, 0x64, 0x6f, 0xe2, 0xcd, 0x0e, 0xb3, 0x6f, 0x24, 0x12, 0x00, 0x65,
	0xb4, 0x5b, 0x90, 0x46, 0xcb, 0xb2, 0x3f, 0xe9, 0xcd, 0x46, 0xf3, 0x69, 0xbc, 0x2d, 0x46, 0x9c,
	0xb4, 0xb7, 0x59, 0x47, 0x26, 0x2e, 0x20, 0x5c, 0x23, 0x33, 0xbe, 0x3e, 0x51, 0x2e, 0x83, 0xda,
	0x7b, 0xd8, 0x10, 0x69, 0x1e, 0x95, 0x10, 0xfe, 0xa8, 0xfe, 0xc5, 0x3e, 0x83, 0xc1, 0x8a, 0xd1,
	0x6e, 0x74, 0x4d, 0xe6, 0x60, 0x03, 0xd3, 0x5c, 0x5c, 0xc1, 0x48, 0xad, 0xd8, 0x99, 0xb2, 0x59,
	0xf6, 0x9a, 0x42, 0x2d, 0x95, 0xe6, 0x9b, 0x42, 0xc6, 0x52, 0x41, 0x5a, 0xf6, 0x1b, 0x61, 0x83,
	0x22, 0x03, 0xc3, 0x0c, 0xb9, 0x32, 0x9a, 0x51, 0x48, 0x18, 0x28, 0x8b, 0x0b, 0x87, 0x8d, 0xe5,
	0x30, 0x6b, 0xa1, 0x48, 0xe1, 0xa8, 0x53, 0x8b, 0xa5, 0x5f, 0x17, 0xbf, 0xd9, 0x59, 0xbc, 0x9d,
	0xb3, 0x3f, 0xd2, 0x28, 0x84, 0x41, 0x86, 0x6f, 0x2b, 0x64, 0x37, 0xff, 0xf4, 0x60, 0xcc, 0x4b,
	0xaa, 0x2a, 0xd2, 0xc5, 0x03, 0xda, 0x35, 0x29, 0x14, 0xcf, 0x70, 0x92, 0xd4, 0xa6, 0xdd, 0xbf,
	0xb7, 0x9f, 0xd1, 0x79, 0xb4, 0xfd, 0xac, 0xed, 0x18, 0x1d, 0x88, 0x47, 0x18, 0xdf, 0xa3, 0xeb,
	0xe8, 0x58, 0x5c, 0xef, 0x12, 0xd6, 0x59, 0xf7, 0xfb, 0xf6, 0x4b, 0x50, 0xbf, 0xcb, 0xbb, 0xaf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x22, 0xec, 0xd7, 0xbe, 0x02, 0x00, 0x00,
}
