// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package app

import (
	"thrgoweb/internal/app/dao/user"
	"thrgoweb/internal/app/router"
	"thrgoweb/internal/app/service"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	routerRouter := &router.Router{}
	engine := InitGinEngine(routerRouter)
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	userRepo := &user.UserRepo{
		DB: db,
	}
	userSrv := &service.UserSrv{
		UserRepo: userRepo,
	}
	injector := &Injector{
		Engine:  engine,
		UserSrv: userSrv,
	}
	return injector, func() {
		cleanup()
	}, nil
}
