FROM alpine:latest


RUN mkdir /app  
 RUN         mkdir /lib64 
  RUN        ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

WORKDIR /app

COPY  consignment-service  /app/consignment-service

# CMD ["./consignment-service"]

